import { createHash, createPrivateKey, createPublicKey, sign, verify } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type Obj = { [key: string]: unknown };

export interface FixtureManifest {
  manifestVersion: 1;
  contractVersion: "tinycloud.share-email-claim/v1";
  files: Record<string, string>;
  testOnly: true;
  manifestDigest: string;
}
export interface FixtureBundle {
  manifest: FixtureManifest;
  positive: unknown;
  negative: unknown;
  states: unknown;
  domains: unknown;
  schemas: unknown;
}

const textEncoder = new TextEncoder();
const b64 = (bytes: Uint8Array): string => Buffer.from(bytes).toString("base64url");
const bytes = (value: string): Uint8Array => new Uint8Array(Buffer.from(value, "base64url"));
const digest = (value: Uint8Array): string => b64(new Uint8Array(createHash("sha256").update(value).digest()));
const utf8 = (value: string): Uint8Array => textEncoder.encode(value);
const record = (value: unknown, label: string): Obj => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label}: expected object`); return value as Obj; };
const list = (value: unknown, label: string): unknown[] => { if (!Array.isArray(value)) throw new Error(`${label}: expected array`); return value; };
const string = (value: unknown, label: string): string => { if (typeof value !== "string") throw new Error(`${label}: expected string`); return value; };
const clone = (value: unknown): Obj => JSON.parse(JSON.stringify(value)) as Obj;
const assert = (condition: boolean, message: string): void => { if (!condition) throw new Error(message); };
const expectReject = (label: string, operation: () => void): void => { let rejected = false; try { operation(); } catch { rejected = true; } assert(rejected, `${label}: expected reject`); };

function jcs(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "string") { for (let i = 0; i < value.length; i++) { const unit = value.charCodeAt(i); if (unit >= 0xd800 && unit <= 0xdbff) { const next = value.charCodeAt(i + 1); if (!(next >= 0xdc00 && next <= 0xdfff)) throw new TypeError("lone surrogate"); i++; } else if (unit >= 0xdc00 && unit <= 0xdfff) throw new TypeError("lone surrogate"); } const encoded = JSON.stringify(value); if (encoded === undefined) throw new TypeError("string encoding"); return encoded; }
  if (typeof value === "number") { if (!Number.isFinite(value) || !Number.isSafeInteger(value) || Object.is(value, -0)) throw new TypeError("unsafe number"); return JSON.stringify(value); }
  if (Array.isArray(value)) return `[${value.map((item) => { if (item === undefined) throw new TypeError("undefined"); return jcs(item); }).join(",")}]`;
  if (typeof value !== "object" || value === undefined || Object.getPrototypeOf(value) !== Object.prototype) throw new TypeError("non-plain value");
  return `{${Object.keys(value).sort().map((key) => { const child = (value as Obj)[key]; if (child === undefined) throw new TypeError("undefined"); return `${JSON.stringify(key)}:${jcs(child)}`; }).join(",")}}`;
}
function strictB64(value: string): Uint8Array { if (!/^[A-Za-z0-9_-]+$/.test(value)) throw new Error("base64url alphabet"); const decoded = bytes(value); assert(b64(decoded) === value, "noncanonical base64url"); return decoded; }
function canonicalEmail(value: unknown): string {
  const email = string(value, "email"); assert(/^[\x21-\x7e]+$/.test(email), "email ASCII/whitespace"); assert((email.match(/@/g) ?? []).length === 1, "email at-sign"); const [local, domain] = email.split("@"); assert(new TextEncoder().encode(local).length <= 64 && new TextEncoder().encode(domain).length <= 253 && new TextEncoder().encode(email).length <= 254, "email byte limits"); assert(/^[A-Za-z0-9!#$%&'*+\-/=?^_`{|}~]+(?:\.[A-Za-z0-9!#$%&'*+\-/=?^_`{|}~]+)*$/.test(local), "email dot atom"); assert(domain.split(".").every((label) => /^[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?$/.test(label) && label.length <= 63), "email domain"); return `${local}@${domain.toLowerCase()}`;
}
function valueAt(root: Obj, path: string): unknown { return path.split(".").reduce<unknown>((current, key) => record(current, path)[key], root); }
function replaceArtifact(scenario: Obj, name: string, field: string, value: unknown, domains: Obj): Obj {
  const altered = clone(scenario); const artifacts = list(altered.artifacts, "artifacts") as Obj[]; const artifact = artifacts.find((candidate) => candidate.name === name); if (!artifact) throw new Error(`missing artifact ${name}`); const message = { ...record(artifact.message, `${name}.message`), [field]: value };
  const registry = record(domains.domains, "domains"); const domain = string(registry[name], `${name}.domain`); const testKeys = record(domains.testKeys, "testKeys"); const seed = name === "inviteAuthorization" ? string(testKeys.nodeSeedHex, "node seed") : string(testKeys.holderSeedHex, "holder seed"); const textMessage = jcs(message); const prefix = Buffer.from("302e020100300506032b657004220420", "hex"); const key = createPrivateKey({ key: Buffer.concat([prefix, Buffer.from(seed, "hex")]), format: "der", type: "pkcs8" }); const signature = new Uint8Array(sign(null, Buffer.concat([utf8(domain), utf8(textMessage)]), key));
  const alteredArtifact = { ...artifact, domain, message, jcs: textMessage, messageDigest: digest(utf8(textMessage)), signedBytesDigest: digest(Buffer.concat([utf8(domain), utf8(textMessage)])), signatureDigest: digest(signature), signature: { ...record(artifact.signature, `${name}.signature`), value: b64(signature) } }; artifacts[artifacts.indexOf(artifact)] = alteredArtifact; if (name === "inviteAuthorization") altered.authorization = message; return altered;
}
function crossEquations(scenario: Obj): void {
  const artifacts = list(scenario.artifacts, "artifacts") as Obj[]; const byName = (name: string): Obj => { const artifact = artifacts.find((item) => item.name === name); if (!artifact) throw new Error(`missing ${name}`); return record(artifact.message, `${name}.message`); }; const auth = record(scenario.authorization, "authorization"); const binding = byName("holderBinding"); const credential = record(scenario.credential, "credential"); const disclosure = list(credential.disclosures, "disclosures").map((value) => record(value, "disclosure"))[0]; const disclosed = JSON.parse(new TextDecoder().decode(strictB64(string(disclosure.encoded, "disclosure.encoded"))) as string) as unknown[];
  assert(string(record(scenario.policy, "policy").recipientEmail, "policy.email") === string(auth.recipientEmail, "authorization.email") && string(auth.recipientEmail, "authorization.email") === string(scenario.canonicalEmail, "canonicalEmail"), "canonical email equation"); assert(disclosure.path === "/email" && disclosure.value === scenario.canonicalEmail && disclosed.length === 3 && disclosed[1] === "email" && disclosed[2] === scenario.canonicalEmail, "disclosed email equation");
  const redeem = record(record(record(scenario.preimages, "preimages").claimRedeemRequest, "claimRedeemRequest").body, "claimRedeemRequest.body"); const otpRedeem = record(record(record(scenario.preimages, "preimages").claimRedeemOtpRequest, "claimRedeemOtpRequest").body, "claimRedeemOtpRequest.body"); assert(redeem.redemptionId === binding.redemptionId && redeem.invitationId === binding.invitationId && otpRedeem.redemptionId === binding.redemptionId && otpRedeem.invitationId === binding.invitationId, "redeem identifier equation");
  const source = record(scenario.source, "source"); const expected: Record<string, unknown> = { shareCid: scenario.shareCid, shareId: scenario.shareId, policyCid: scenario.policyCid, targetOrigin: auth.targetOrigin, nodeAudience: auth.nodeAudience, holderDid: binding.holderDid, contentSourceDigest: scenario.sourceDigest, action: source.action, resource: source.path };
  const check = (value: Obj): void => { for (const field of Object.keys(expected)) if (value[field] !== undefined) assert(value[field] === expected[field], `${field} equation`); if (value.contentSource !== undefined) assert(jcs(value.contentSource) === jcs(source), "content source equation"); };
  for (const artifact of artifacts) check(record(artifact.message, "artifact.message")); const envelope = record(scenario.envelope, "envelope"); assert(envelope.shareId === expected.shareId && record(envelope.authorizationTarget, "authorizationTarget").policyCid === expected.policyCid && record(envelope.target, "target").origin === expected.targetOrigin && record(envelope.target, "target").nodeAudience === expected.nodeAudience && record(record(envelope.target, "target").resource, "resource").path === expected.resource, "envelope equation"); const enrollment = record(scenario.enrollment, "enrollment"); assert(enrollment.targetOrigin === expected.targetOrigin && enrollment.nodeAudience === expected.nodeAudience, "enrollment equation");
  for (const value of Object.values(record(scenario.preimages, "preimages"))) { const body = record(value, "preimage").body; check(record(body, "preimage.body")); for (const nested of [record(body, "preimage.body").authorization, record(body, "preimage.body").binding, record(body, "preimage.body").challenge, record(body, "preimage.body").presentation, record(body, "preimage.body").session, record(body, "preimage.body").invocation]) if (nested) check(record(nested, "nested preimage")); }
}

function validateRecovery(states: Obj): void {
  const recovery = record(states.issuanceRecovery, "issuanceRecovery");
  assert(recovery.seedCiphertext === recovery.retrySeedCiphertext && recovery.pendingSeedCiphertext === recovery.retryPendingSeedCiphertext && recovery.seedCiphertext === recovery.pendingSeedCiphertext, "retry seed bytes changed");
  const timeline = list(recovery.timeline, "recovery.timeline").map((value) => record(value, "recovery event"));
  assert(timeline.length === 5 && timeline[0].state === "PENDING_ENCRYPTED" && timeline[1].event === "credential_generated_then_crash" && timeline[1].credentialGenerated === true && timeline[1].durableCompletion === false && timeline[2].event === "retry_same_seed" && timeline[3].durableCompletion === true && timeline[3].durableCompletionAt === "2026-07-16T12:00:03.000Z" && timeline[3].resultPersisted === true && timeline[4].state === "CONSUMED" && timeline[4].consumedPersisted === true && timeline[4].resultPersisted === true && timeline[4].atomicConsumedAndResult === true && timeline[4].resultDigest === recovery.resultDigest, "recovery timeline");
  assert(timeline[0].seedEncrypted === true && timeline[1].seedEncrypted === true && timeline[2].seedEncrypted === true && timeline[4].seedEncrypted === false, "recovery seed lifecycle");
  const failure = list(recovery.terminalFailureTimeline, "terminalFailureTimeline").map((value) => record(value, "terminal failure event"));
  assert(failure.length === 3 && failure[0].state === "PENDING_ENCRYPTED" && failure[0].seedEncrypted === true && failure[1].state === "RETRYING" && failure[1].seedEncrypted === true && failure[2].state === "TERMINAL_ERROR" && failure[2].terminalErrorPersisted === true && failure[2].seedEncrypted === false && failure[2].atomicTerminalAndSeedDeletion === true && failure[2].errorCode === "credential_issuance_failed", "atomic terminal failure");
  const invariants = record(recovery.invariants, "recovery invariants");
  for (const key of ["pendingSeedEncrypted", "retrySeedByteIdentical", "completionRequiresDurableWrite", "consumedAndResultPersistedAtomically", "terminalResolutionAtomic", "cleanupRefusesPendingSeed"]) assert(invariants[key] === true, `${key}: invariant`);
  assert(invariants.durableCompletionAt === "2026-07-16T12:00:03.000Z" && invariants.redactionWindowSeconds === 900 && invariants.redactionStartsOnlyAt === "durable_completion" && invariants.redactionMeasuredFrom === "2026-07-16T12:00:03.000Z" && invariants.redactionAt === "2026-07-16T12:15:03.000Z", "redaction window");
  const cleanup = record(recovery.cleanup, "cleanup");
  assert(cleanup.pendingSeedAction === "refuse" && cleanup.pendingSeedRemains === true && cleanup.completedSeedAction === "delete", "cleanup policy");
  const terminal = record(recovery.terminalResolution, "terminal resolution");
  assert(terminal.atomic === true && terminal.atomicConsumedAndResultPersisted === true && terminal.atomicTerminalAndSeedDeletion === true && terminal.successOutcome === "CONSUMED" && terminal.failureOutcome === "TERMINAL_ERROR", "terminal resolution");
  assert(digest(utf8(new TextDecoder().decode(strictB64(string(recovery.resultBytes, "resultBytes"))))) === recovery.resultDigest, "result digest");
}

const b58Alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
const negativeIds = new Set([
  "leading-space", "trailing-space", "tab", "newline", "inner-space", "leading-dot-local", "trailing-dot-local", "repeated-dot-local", "empty-local", "empty-domain", "multiple-at", "quoted-local", "comment-local", "backslash-local", "angle-form", "unicode-local", "unicode-domain", "local-over-64", "label-over-63", "empty-domain-label", "trailing-domain-dot", "leading-hyphen", "trailing-hyphen", "domain-over-253", "total-over-254", "policy-cid-is-real", "policy-bytes-self-policy-cid", "share-cid-is-real", "sealed-blob-aead-tamper", "envelope-policy-target-missing-kind", "envelope-policy-target-missing-bytes", "envelope-policy-target-mismatch", "envelope-origin-mismatch", "authorization-recipient-email-mismatch", "redeem-redemption-id-mismatch", "redeem-invitation-id-mismatch", "share-id-propagation", "share-cid-propagation", "policy-cid-propagation", "target-origin-propagation", "node-audience-propagation", "holder-did-propagation", "content-source-digest-propagation", "action-propagation", "resource-propagation", "envelope-domain-from-unregistered-label", "jcs-lone-surrogate", "jcs-unsafe-number", "jcs-fractional-number", "jcs-negative-zero", "jcs-undefined", "noncanonical-b64url-16-tail", "noncanonical-b64url-64-tail", "noncanonical-holder-kid", "small-order-did-key", "noncanonical-ed25519-s", "short-signature", "wrong-source-digest", "sql-arguments-too-large", "sql-arbitrary-query-field", "policy-action-source-mismatch", "content-source-propagation", "credential-sub-mismatch", "credential-legacy-email-path", "credential-unsupported-status", "different-holder-valid-signature", "policy-challenge-replay", "session-token-only", "old-secret-after-resend", "otp-after-five-wrong", "scanner-get", "resend-recipient-supplied-email", "capability-extra-route", "capability-wildcard-origin", "read-body-one-field-mutation", "claim-redeem-magic-with-otp", "claim-redeem-otp-with-magic", "policy-challenge-response-proof", "policy-session-response-proof", "sd-jwt-missing-alg", "sd-jwt-two-element-disclosure",
]);

function base58Decode(value: string): Uint8Array {
  assert(/^[1-9A-HJ-NP-Za-km-z]+$/.test(value), "base58 alphabet");
  let number = 0n;
  for (const character of value) { const digit = b58Alphabet.indexOf(character); assert(digit >= 0, "base58 digit"); number = number * 58n + BigInt(digit); }
  let hex = number.toString(16); if (hex.length % 2) hex = `0${hex}`;
  const decoded = hex.length === 0 ? new Uint8Array() : new Uint8Array(Buffer.from(hex, "hex"));
  let leadingZeroes = 0; while (leadingZeroes < value.length && value[leadingZeroes] === "1") leadingZeroes++;
  return leadingZeroes === 0 ? decoded : new Uint8Array([...new Uint8Array(leadingZeroes), ...decoded]);
}
function validateDidKey(value: unknown, label: string): string {
  const did = string(value, label); assert(/^did:key:z[1-9A-HJ-NP-Za-km-z]+$/.test(did), `${label}: did:key`);
  const encoded = did.slice("did:key:z".length); const key = base58Decode(encoded); assert(key.length === 34 && key[0] === 0xed && key[1] === 0x01, `${label}: Ed25519 multicodec`);
  const publicKey = key.slice(2); const yBytes = new Uint8Array(publicKey); yBytes[31] &= 0x7f; const y = littleEndianNumber(yBytes);
  assert(y < (1n << 255n) - 19n, `${label}: noncanonical Edwards point`);
  assert(!(publicKey[0] === 1 && publicKey.slice(1).every((byte) => byte === 0)), `${label}: small-order Edwards point`);
  return did;
}
function validateFixedB64(value: unknown, length: number, label: string): Uint8Array { const decoded = strictB64(string(value, label)); assert(decoded.length === length, `${label}: byte length`); return decoded; }
function littleEndianNumber(value: Uint8Array): bigint { let number = 0n; for (let index = value.length - 1; index >= 0; index--) number = (number << 8n) | BigInt(value[index]); return number; }
function validateEd25519Signature(value: unknown, label: string): Uint8Array {
  const signature = validateFixedB64(value, 64, label); const scalar = signature.slice(32); const order = 0x1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3edn;
  assert((scalar[31] & 0xe0) === 0 && littleEndianNumber(scalar) > 0n && littleEndianNumber(scalar) < order, `${label}: noncanonical Ed25519 S`); return signature;
}
function verifyEd25519(value: unknown, did: unknown, domain: string, message: Obj, label: string): void {
  const signature = validateEd25519Signature(value, label); const holderDid = validateDidKey(did, `${label}.did`); const keyBytes = base58Decode(holderDid.slice("did:key:z".length)).slice(2); const key = createPublicKey({ key: Buffer.concat([Buffer.from("302a300506032b6570032100", "hex"), keyBytes]), format: "der", type: "spki" });
  assert(verify(null, Buffer.concat([utf8(domain), utf8(jcs(message))]), key, signature), `${label}: signature verification`);
}
function validateProof(value: unknown, label: string, expectedKid?: string): void {
  const proof = record(value, label); assert(proof.alg === "EdDSA", `${label}: algorithm`); const kid = string(proof.kid, `${label}.kid`); assert(kid.includes("#") && !/\s/.test(kid), `${label}: kid shape`); if (kid.startsWith("did:key:")) validateDidKey(kid.split("#", 1)[0], `${label}.kid.did`); if (expectedKid !== undefined) assert(kid === expectedKid, `${label}: key binding`); validateEd25519Signature(proof.signature, `${label}.signature`);
}
function base32Decode(value: string): Uint8Array {
  assert(/^[a-z2-7]+$/.test(value), "CID base32"); const alphabet = "abcdefghijklmnopqrstuvwxyz234567"; let bits = 0; let buffer = 0; const output: number[] = [];
  for (const character of value) { buffer = (buffer << 5) | alphabet.indexOf(character); bits += 5; if (bits >= 8) { bits -= 8; output.push((buffer >> bits) & 0xff); } }
  return new Uint8Array(output);
}
function validateCidBytes(cid: unknown, value: Uint8Array, label: string): void { const text = string(cid, label); const multihash = base32Decode(text.slice(1)); assert(text.startsWith("b") && multihash.length === 36 && multihash[0] === 0x01 && multihash[1] === 0x55 && multihash[2] === 0x12 && multihash[3] === 0x20, `${label}: CID shape`); const actual = new Uint8Array(createHash("sha256").update(value).digest()); assert(Buffer.from(actual).equals(Buffer.from(multihash.slice(4))), `${label}: CID digest`); }
function validatePolicyBytes(target: Obj, label: string): void { const policyBytes = strictB64(string(target.policyBytes, `${label}.policyBytes`)); const text = new TextDecoder().decode(policyBytes); const policy = record(JSON.parse(text) as unknown, `${label}.policy`); assert(jcs(policy) === text, `${label}: policy bytes are not JCS`); validateCidBytes(target.policyCid, policyBytes, `${label}.policyCid`); }
function validateEnvelopeTarget(target: Obj, label: string): void { assert(target.kind === "policy", `${label}: kind`); string(target.policyCid, `${label}.policyCid`); validatePolicyBytes(target, label); }
function validateArtifactEncoding(artifact: Obj, domains: Obj, scenario: Obj): void {
  const name = string(artifact.name, "artifact.name"); const registry = record(domains.domains, "domains"); const message = record(artifact.message, `${name}.message`); const domain = string(registry[name], `${name}.domain`); assert(artifact.domain === domain && artifact.jcs === jcs(message), `${name}: JCS/domain`); assert(artifact.messageDigest === digest(utf8(string(artifact.jcs, `${name}.jcs`))), `${name}: message digest`); const signature = record(artifact.signature, `${name}.signature`); validateProof(signature, `${name}.signature`); const signatureBytes = strictB64(string(signature.value, `${name}.signature.value`)); assert(artifact.signedBytesDigest === digest(Buffer.concat([utf8(domain), utf8(string(artifact.jcs, `${name}.jcs`))])) && artifact.signatureDigest === digest(signatureBytes), `${name}: signed bytes digest`);
  if (name === "holderBinding" || name === "policyPresentation" || name === "readInvocation") { const holderDid = validateDidKey(message.holderDid, `${name}.holderDid`); assert(string(signature.kid, `${name}.kid`) === `${holderDid}#${holderDid.slice("did:key:".length)}`, `${name}: holder key binding`); }
  if (name === "policy") { const issuerDid = validateDidKey(message.issuerDid, `${name}.issuerDid`); assert(string(signature.kid, `${name}.kid`) === `${issuerDid}#${issuerDid.slice("did:key:".length)}`, `${name}: issuer key binding`); }
  if (name === "inviteAuthorization") assert(string(signature.kid, `${name}.kid`) === string(record(scenario.enrollment, "enrollment").invitationKid, `${name}.invitationKid`), `${name}: invitation key binding`);
}
function validateSource(source: Obj, scenario: Obj, label: string): void {
  assert(source.kind === scenario.kind && source.action === (scenario.kind === "kv" ? "tinycloud.kv/get" : "tinycloud.sql/read"), `${label}: source action`); assert(digest(utf8(jcs(source))) === scenario.sourceDigest, `${label}: source digest`);
  if (scenario.kind === "sql") { const args = record(source.arguments, `${label}.arguments`); assert(digest(utf8(jcs(args))) === source.argumentsDigest, `${label}: SQL arguments digest`); assert(utf8(jcs(args)).length <= 4096, `${label}: SQL arguments limit`); }
}
function validateCredentialProfile(credential: Obj, scenario: Obj, label: string): void {
  assert(credential.format === "vc+sd-jwt" && credential.vct === "opencredentials.email/v1", `${label}: credential format`); const holderDid = validateDidKey(credential.holderDid, `${label}.holderDid`); const claims = record(credential.claims, `${label}.claims`); const claimKeys = ["iss", "sub", "iat", "nbf", "exp", "jti", "vct", "tinycloud_share", "_sd_alg", "_sd"]; assert(Object.keys(claims).length === claimKeys.length && Object.keys(claims).every((key) => claimKeys.includes(key)), `${label}: strict claim shape`); assert(claims.sub === holderDid && claims.vct === credential.vct && claims._sd_alg === "sha-256", `${label}: claim binding`); const sd = list(claims._sd, `${label}._sd`); assert(sd.length === 1, `${label}: SD-JWT digest count`); const disclosures = list(credential.disclosures, `${label}.disclosures`); assert(disclosures.length === 1, `${label}: disclosure count`); const disclosure = record(disclosures[0], `${label}.disclosure`); assert(disclosure.path === "/email" && canonicalEmail(disclosure.value) === scenario.canonicalEmail, `${label}: email disclosure`); const encoded = string(disclosure.encoded, `${label}.encoded`); const tuple = JSON.parse(new TextDecoder().decode(strictB64(encoded))) as unknown[]; assert(tuple.length === 3 && tuple[1] === "email" && tuple[2] === scenario.canonicalEmail && disclosure.digest === digest(utf8(encoded)) && sd[0] === disclosure.digest, `${label}: disclosure digest`); }
function validateReadBody(body: Obj, scenario: Obj, label: string): void { const required = ["sessionId", "contentSource", "contentSourceDigest", "action", "resource", "requestBodyDigest", "invocation", "proof"]; assert(Object.keys(body).every((key) => required.includes(key)) && required.every((key) => Object.hasOwn(body, key)), `${label}: strict read shape`); validateSource(record(body.contentSource, `${label}.contentSource`), scenario, `${label}.contentSource`); assert(body.contentSourceDigest === scenario.sourceDigest && body.action === record(scenario.source, "source").action && body.resource === record(scenario.source, "source").path, `${label}: source binding`); validateProof(body.proof, `${label}.proof`); }
function validateRedeemBody(body: Obj, scenario: Obj, label: string): void { const keys = ["version", "redemptionId", "invitationId", "method", "mailboxProof", "binding", "holderProof"]; assert(Object.keys(body).length === keys.length && keys.every((key) => Object.hasOwn(body, key)), `${label}: strict redeem shape`); assert(body.version === "tinycloud.share-email-claim/v1", `${label}: version`); validateFixedB64(body.redemptionId, 16, `${label}.redemptionId`); validateFixedB64(body.invitationId, 16, `${label}.invitationId`); if (body.method === "magic") validateFixedB64(body.mailboxProof, 32, `${label}.mailboxProof`); else if (body.method === "otp") assert(typeof body.mailboxProof === "string" && /^[0-9]{6}$/.test(body.mailboxProof), `${label}: OTP shape`); else throw new Error(`${label}: method`); const binding = record(body.binding, `${label}.binding`); const holderDid = validateDidKey(binding.holderDid, `${label}.binding.holderDid`); assert(binding.shareId === scenario.shareId && binding.shareCid === scenario.shareCid && binding.policyCid === scenario.policyCid, `${label}: binding equations`); validateProof(body.holderProof, `${label}.holderProof`, `${holderDid}#${holderDid.slice("did:key:".length)}`); }
function validateCapability(capability: Obj, original: Obj, label: string): void { const origin = string(capability.origin, `${label}.origin`); const parsed = new URL(origin); assert(parsed.protocol === "https:" && !origin.includes("*") && capability.version === 1, `${label}: origin/version`); const routes = list(capability.routes, `${label}.routes`).map((route) => string(route, `${label}.route`)); const originalRoutes = new Set(list(original.routes, `${label}.originalRoutes`).map((route) => string(route, `${label}.originalRoute`))); assert(new Set(routes).size === routes.length && routes.every((route) => originalRoutes.has(route)), `${label}: route allowlist`); }
function validateTransition(states: Obj, from: string, to: string): void { const known = new Set(list(states.nonce, "states.nonce").map((value) => string(value, "nonce state"))); assert(known.has(from) && known.has(to), "nonce state vocabulary"); const allowed = (from === "ISSUED" && to === "VERIFYING") || (from === "VERIFYING" && to === "CONSUMED"); assert(allowed, "invalid nonce transition"); }
function validateResponseProof(scenario: Obj, data: Obj, responseName: string): void { const preimages = record(scenario.preimages, "preimages"); const candidate = clone(record(record(preimages[responseName], responseName).body, `${responseName}.body`)); const proof = record(candidate.proof, `${responseName}.proof`); const signer = validateDidKey(data.signer, `${responseName}.mutation.signer`); candidate.proof = { ...proof, kid: `${signer}#${signer.slice("did:key:".length)}` }; validateProof(candidate.proof, `${responseName}.proof`, string(record(scenario.enrollment, "enrollment").invitationKid, "enrollment.invitationKid")); }

function executeNegative(row: Obj, scenario: Obj, domains: Obj, states: Obj): void {
  const id = string(row.id, "negative.id"); const data = record(row.mutationData, `${id}.mutationData`); const artifacts = list(scenario.artifacts, "artifacts") as Obj[];
  switch (id) {
    case "leading-space": case "trailing-space": case "tab": case "newline": case "inner-space": case "leading-dot-local": case "trailing-dot-local": case "repeated-dot-local": case "empty-local": case "empty-domain": case "multiple-at": case "quoted-local": case "comment-local": case "backslash-local": case "angle-form": case "unicode-local": case "unicode-domain": case "local-over-64": case "label-over-63": case "empty-domain-label": case "trailing-domain-dot": case "leading-hyphen": case "trailing-hyphen": case "domain-over-253": case "total-over-254": expectReject(id, () => canonicalEmail(data.input)); break;
    case "policy-cid-is-real": expectReject(id, () => { const target = { ...record(record(scenario.envelope, "envelope").authorizationTarget, "authorizationTarget"), policyBytes: b64(utf8(string(data.replacement, id))) }; validateEnvelopeTarget(target, id); }); break;
    case "policy-bytes-self-policy-cid": expectReject(id, () => { const policy = { ...record(scenario.policy, "policy"), [string(data.property, id)]: data.value }; const target = { ...record(record(scenario.envelope, "envelope").authorizationTarget, "authorizationTarget"), policyBytes: b64(utf8(jcs(policy))) }; validateEnvelopeTarget(target, id); }); break;
    case "share-cid-is-real": case "sealed-blob-aead-tamper": expectReject(id, () => { const blob = strictB64(string(scenario.sealedBlob, "sealedBlob")); blob[blob.length - 1] ^= 1; validateCidBytes(scenario.shareCid, blob, id); }); break;
    case "envelope-policy-target-missing-kind": case "envelope-policy-target-missing-bytes": expectReject(id, () => { const target = { ...record(record(scenario.envelope, "envelope").authorizationTarget, "authorizationTarget") }; delete target[id.endsWith("kind") ? "kind" : "policyBytes"]; validateEnvelopeTarget(target, id); }); break;
    case "envelope-policy-target-mismatch": expectReject(id, () => { const mutationTarget = { ...record(record(scenario.envelope, "envelope").authorizationTarget, "authorizationTarget"), policyCid: data.policyCid, policyBytes: data.policyBytes }; validateEnvelopeTarget(mutationTarget, id); }); break;
    case "envelope-origin-mismatch": expectReject(id, () => { const envelope = clone(record(scenario.envelope, "envelope")); const target = record(envelope.target, "target"); target.origin = data.value; crossEquations({ ...scenario, envelope }); }); break;
    case "authorization-recipient-email-mismatch": expectReject(id, () => { const altered = replaceArtifact(scenario, "inviteAuthorization", "recipientEmail", data.value, domains); validateArtifactEncoding(record((list(altered.artifacts, "artifacts") as Obj[]).find((item) => item.name === "inviteAuthorization"), "altered authorization"), domains, scenario); crossEquations(altered); }); break;
    case "redeem-redemption-id-mismatch": case "redeem-invitation-id-mismatch": expectReject(id, () => { const altered = replaceArtifact(scenario, "holderBinding", id.includes("redemption") ? "redemptionId" : "invitationId", data.value, domains); const binding = record((list(altered.artifacts, "artifacts") as Obj[]).find((item) => item.name === "holderBinding"), "altered holder binding"); validateArtifactEncoding(binding, domains, scenario); crossEquations(altered); }); break;
    case "share-id-propagation": case "share-cid-propagation": case "policy-cid-propagation": case "target-origin-propagation": case "node-audience-propagation": case "holder-did-propagation": case "content-source-digest-propagation": case "action-propagation": case "resource-propagation": { const field: Record<string, string> = { "share-id-propagation": "shareId", "share-cid-propagation": "shareCid", "policy-cid-propagation": "policyCid", "target-origin-propagation": "targetOrigin", "node-audience-propagation": "nodeAudience", "holder-did-propagation": "holderDid", "content-source-digest-propagation": "contentSourceDigest", "action-propagation": "action", "resource-propagation": "resource" }; const values = data.valueByKind === undefined ? undefined : record(data.valueByKind, id); const value = values?.[String(scenario.kind)] ?? data.value; expectReject(id, () => { const altered = replaceArtifact(scenario, "policyPresentation", field[id], value, domains); const presentation = record((list(altered.artifacts, "artifacts") as Obj[]).find((item) => item.name === "policyPresentation"), "altered presentation"); validateArtifactEncoding(presentation, domains, scenario); crossEquations(altered); }); break; }
    case "envelope-domain-from-unregistered-label": expectReject(id, () => { const registry = record(record(domains, "domains").domains, "domains"); assert(string(data.value, id) === string(registry.envelope, "envelope domain"), "unregistered envelope domain"); }); break;
    case "jcs-lone-surrogate": expectReject(id, () => jcs(JSON.parse(string(data.jsonLiteral, id)))); break;
    case "jcs-unsafe-number": case "jcs-fractional-number": case "jcs-negative-zero": expectReject(id, () => { const literal = string(data.jsonLiteral, id); const candidate = literal === "-0" ? -0 : JSON.parse(literal) as unknown; jcs(candidate); }); break;
    case "jcs-undefined": expectReject(id, () => jcs(undefined)); break;
    case "noncanonical-b64url-16-tail": case "noncanonical-b64url-64-tail": expectReject(id, () => validateFixedB64(data.value, id.includes("16") ? 16 : 64, id)); break;
    case "noncanonical-holder-kid": expectReject(id, () => { const holder = record((artifacts.find((item) => item.name === "holderBinding")), "holderBinding"); const signature = record(holder.signature, "holderBinding.signature"); const candidate = { ...signature, kid: data.value }; validateProof(candidate, id, `${string(record(holder.message, "holderBinding.message").holderDid, "holderDid")}#${string(record(holder.message, "holderBinding.message").holderDid, "holderDid").slice("did:key:".length)}`); }); break;
    case "small-order-did-key": expectReject(id, () => { const holder = record((artifacts.find((item) => item.name === "holderBinding")), "holderBinding"); validateDidKey(data.value, id); validateArtifactEncoding({ ...holder, message: { ...record(holder.message, "holderBinding.message"), holderDid: data.value } }, domains, scenario); }); break;
    case "noncanonical-ed25519-s": expectReject(id, () => { const holder = record(artifacts.find((item) => item.name === "holderBinding"), "holderBinding"); const message = record(holder.message, "holderBinding.message"); verifyEd25519(data.value, message.holderDid, string(record(domains.domains, "domains").holderBinding, "holderBinding.domain"), message, id); }); break;
    case "short-signature": expectReject(id, () => { const read = record((artifacts.find((item) => item.name === "readInvocation")), "readInvocation"); const signature = record(read.signature, "readInvocation.signature"); validateEd25519Signature(b64(validateFixedB64(signature.value, 64, id).slice(0, Number(data.bytes))), id); }); break;
    case "wrong-source-digest": expectReject(id, () => { const preimage = record(record(scenario.preimages, "preimages").sqlReadRequest, "sqlReadRequest"); const body = clone(record(preimage.body, "sqlReadRequest.body")); const source = record(body.contentSource, "sqlReadRequest.contentSource"); const args = { ...record(source.arguments, "sqlReadRequest.arguments"), document_id: data.value }; source.arguments = args; validateSource(source, scenario, id); }); break;
    case "sql-arguments-too-large": expectReject(id, () => { const preimage = record(record(scenario.preimages, "preimages").sqlReadRequest, "sqlReadRequest"); const body = clone(record(preimage.body, "sqlReadRequest.body")); const source = record(body.contentSource, "sqlReadRequest.contentSource"); source.arguments = { ...record(source.arguments, "sqlReadRequest.arguments"), [string(data.field, id)]: data.value }; validateSource(source, scenario, id); }); break;
    case "sql-arbitrary-query-field": expectReject(id, () => { const preimage = record(record(scenario.preimages, "preimages").sqlReadRequest, "sqlReadRequest"); const body = { ...clone(record(preimage.body, "sqlReadRequest.body")), [string(data.field, id)]: data.value }; validateReadBody(body, scenario, id); }); break;
    case "policy-action-source-mismatch": expectReject(id, () => { const values = record(data.valueByKind, id); const policy = clone(record(scenario.policy, "policy")); policy.action = values[String(scenario.kind)]; const source = record(policy.contentSource, "policy.contentSource"); assert(policy.action === source.action && policy.action === record(scenario.source, "source").action, `${id}: action/source equation`); }); break;
    case "content-source-propagation": expectReject(id, () => { const altered = replaceArtifact(scenario, "policyPresentation", "contentSource", { ...record(scenario.source, "source"), path: data.value }, domains); const presentation = record((list(altered.artifacts, "artifacts") as Obj[]).find((item) => item.name === "policyPresentation"), "altered presentation"); validateArtifactEncoding(presentation, domains, scenario); crossEquations(altered); }); break;
    case "credential-sub-mismatch": expectReject(id, () => { const credential = clone(record(scenario.credential, "credential")); const claims = record(credential.claims, "credential.claims"); claims.sub = data.value; validateCredentialProfile(credential, scenario, id); }); break;
    case "credential-legacy-email-path": expectReject(id, () => { const credential = clone(record(scenario.credential, "credential")); const disclosure = record(list(credential.disclosures, "credential.disclosures")[0], "credential.disclosure"); disclosure.path = data.value; validateCredentialProfile(credential, scenario, id); }); break;
    case "credential-unsupported-status": expectReject(id, () => { const credential = clone(record(scenario.credential, "credential")); const claims = record(credential.claims, "credential.claims"); claims.status = data.value; validateCredentialProfile(credential, scenario, id); }); break;
    case "different-holder-valid-signature": expectReject(id, () => { const altered = replaceArtifact(scenario, "holderBinding", "holderDid", data.value, domains); const binding = record((list(altered.artifacts, "artifacts") as Obj[]).find((item) => item.name === "holderBinding"), "altered holder binding"); validateArtifactEncoding(binding, domains, scenario); crossEquations(altered); }); break;
    case "policy-challenge-replay": expectReject(id, () => validateTransition(states, string(data.from, id), string(data.to, id))); break;
    case "session-token-only": expectReject(id, () => { const name = scenario.kind === "sql" ? "sqlReadRequest" : "kvReadRequest"; const body = clone(record(record(record(scenario.preimages, "preimages")[name], name).body, `${name}.body`)); delete body.proof; validateReadBody(body, scenario, id); }); break;
    case "old-secret-after-resend": expectReject(id, () => { const resend = record(list(states.delivery, "states.delivery").find((value) => record(value, "delivery").name === "resend-accepted"), "resend-accepted"); const active = list(record(resend, "resend-accepted").events, "resend.events").find((event) => Array.isArray(event) && event[1] === "ACTIVE(v2)"); assert(active !== undefined && Number(data.value) === 2, `${id}: stale secret version`); }); break;
    case "otp-after-five-wrong": expectReject(id, () => { const semantics = record(states.semantics, "states.semantics"); const otp = record(semantics.otp, "states.semantics.otp"); assert(Number.isInteger(data.value) && Number(data.value) < Number(otp.wrongAttemptsBeforeLock), `${id}: OTP locked state`); }); break;
    case "scanner-get": expectReject(id, () => { const url = new URL(string(data.value, id)); const fragment = new URLSearchParams(url.hash.slice(1)); validateFixedB64(fragment.get("k"), 32, `${id}.k`); validateFixedB64(fragment.get("i"), 16, `${id}.i`); validateFixedB64(fragment.get("c"), 32, `${id}.c`); const operations = list(states.operations, "states.operations"); assert(operations.includes("scanner_get_no_state_change") && data.operation !== "consume-on-GET", `${id}: GET state transition`); }); break;
    case "resend-recipient-supplied-email": expectReject(id, () => { const original = record(record(record(scenario.preimages, "preimages").resendRequest, "resendRequest").body, "resendRequest.body"); const body = { ...original, [string(data.field, id)]: data.value }; assert(Object.keys(body).length === 2 && Object.keys(body).every((key) => key === "invitationId" || key === "claimSecret"), `${id}: strict resend shape`); }); break;
    case "capability-extra-route": case "capability-wildcard-origin": expectReject(id, () => { const capabilities = record(record(domains, "domains").capabilities, "capabilities"); const original = record(capabilities.witness, "witness capability"); const candidate = clone(original); if (id === "capability-extra-route") candidate.routes = [...list(original.routes, "witness.routes"), data.value]; else candidate.origin = data.value; validateCapability(candidate, original, id); }); break;
    case "read-body-one-field-mutation": expectReject(id, () => { const preimage = record(record(scenario.preimages, "preimages").sqlReadRequest, "sqlReadRequest"); const body = { ...clone(record(preimage.body, "sqlReadRequest.body")), resource: data.value }; validateReadBody(body, scenario, id); assert(string(preimage.digest, `${id}.digest`) === digest(utf8(jcs(body))), `${id}: request body digest`); }); break;
    case "claim-redeem-magic-with-otp": expectReject(id, () => { const source = record(record(record(scenario.preimages, "preimages").claimRedeemRequest, "claimRedeemRequest").body, "claimRedeemRequest.body"); const body = clone(source); body.mailboxProof = data.value; validateRedeemBody(body, scenario, id); }); break;
    case "claim-redeem-otp-with-magic": expectReject(id, () => { const source = record(record(record(scenario.preimages, "preimages").claimRedeemOtpRequest, "claimRedeemOtpRequest").body, "claimRedeemOtpRequest.body"); const body = clone(source); body.mailboxProof = data.value; validateRedeemBody(body, scenario, id); }); break;
    case "policy-challenge-response-proof": case "policy-session-response-proof": expectReject(id, () => validateResponseProof(scenario, data, id.startsWith("policy-challenge") ? "policyChallengeResponse" : "policySessionResponse")); break;
    case "sd-jwt-missing-alg": expectReject(id, () => { const credential = clone(record(scenario.credential, "credential")); const claims = record(credential.claims, "credential.claims"); delete claims._sd_alg; validateCredentialProfile(credential, scenario, id); }); break;
    case "sd-jwt-two-element-disclosure": expectReject(id, () => { const shape = list(data.arrayShape, id); assert(shape.length === 3 && shape[1] === "email" && shape[2] === scenario.canonicalEmail, `${id}: disclosure tuple shape`); }); break;
    default: throw new Error(`unknown negative dispatch ${id}`);
  }
}

function validateNegativeNative(positive: Obj, negative: Obj, domains: Obj, states: Obj): void {
  const rows = list(negative.cases, "negative.cases").map((value) => record(value, "negative row")); const seen = new Set<string>(); for (const row of rows) { const id = string(row.id, "negative.id"); assert(negativeIds.has(id), `unknown negative dispatch ${id}`); assert(!seen.has(id), `duplicate negative ${id}`); seen.add(id); assert(row.expected === "reject", `${id}: expected reject marker`); assert(!JSON.stringify(row).includes("scenario."), `${id}: symbolic placeholder`); const applies = list(row.appliesTo, `${id}.appliesTo`); assert(applies.length > 0, `${id}: appliesTo`); for (const scenarioValue of list(positive.scenarios, "positive.scenarios")) { const scenario = record(scenarioValue, "scenario"); if (applies.includes(scenario.kind)) executeNegative(row, scenario, domains, states); } }
}

/** Loads, verifies, and natively executes the complete language-neutral matrix. */
export async function loadFixtureBundle(baseDir = dirname(fileURLToPath(import.meta.url))): Promise<FixtureBundle> {
  const manifest = await readJson<FixtureManifest>(resolve(baseDir, "manifest.json")); const { manifestDigest: _ignored, ...manifestCore } = manifest; assert(manifest.manifestDigest === digest(utf8(jcs(manifestCore))), "manifest digest mismatch"); const specDir = resolve(baseDir, "../../../specs/email-claim-v1"); for (const [name, expected] of Object.entries(manifest.files)) { const path = name === "README.md" || name === "domains.json" || name === "schemas.json" ? resolve(specDir, name) : resolve(baseDir, name); assert(digest(await readFile(path)) === expected, `manifest file mismatch: ${name}`); }
  const positive = await readJson(resolve(baseDir, "positive.json")); const negative = await readJson(resolve(baseDir, "negative.json")); const states = await readJson(resolve(baseDir, "states.json")); const domains = await readJson(resolve(specDir, "domains.json")); const schemas = await readJson(resolve(specDir, "schemas.json")); const positiveObject = record(positive, "positive"); const stateObject = record(states, "states"); const scenarios = list(positiveObject.scenarios, "positive.scenarios").map((value) => record(value, "scenario")); assert(scenarios.length === 2, "positive scenario count"); for (const scenario of scenarios) crossEquations(scenario); validateRecovery(stateObject); validateNegativeNative(positiveObject, record(negative, "negative"), record(domains, "domains"), stateObject); return { manifest, positive, negative, states, domains, schemas };
}

async function readJson<T>(path: string): Promise<T> { return JSON.parse(await readFile(path, "utf8")) as T; }

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) loadFixtureBundle().then(({ manifest, negative }) => console.log(`email-claim-v1 loader: ${manifest.manifestDigest} (${list(record(negative, "negative").cases, "cases").length} native negative rows)`)).catch((error: unknown) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
