#!/usr/bin/env node
/* Self-contained executable contract verifier. No npm dependency. */
import { createDecipheriv, createHash, createPrivateKey, createPublicKey, sign, verify } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const spec = resolve(here, "../../../specs/email-claim-v1");
const enc = new TextEncoder();
const utf8 = (s) => enc.encode(s);
const b64 = (bytes) => Buffer.from(bytes).toString("base64url");
const sha = (bytes) => new Uint8Array(createHash("sha256").update(bytes).digest());
const digest = (bytes) => b64(sha(bytes));
const clone = (value) => JSON.parse(JSON.stringify(value));
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const equal = (a, b, message) => assert(jcs(a) === jcs(b), message);
const load = async (name) => JSON.parse(await readFile(resolve(name), "utf8"));

function jcs(value) {
  if (value === null) return "null";
  if (typeof value === "string") {
    for (let i = 0; i < value.length; i++) { const c = value.charCodeAt(i); if (c >= 0xd800 && c <= 0xdbff) { const n = value.charCodeAt(i + 1); if (!(n >= 0xdc00 && n <= 0xdfff)) throw new TypeError("lone surrogate"); i++; } else if (c >= 0xdc00 && c <= 0xdfff) throw new TypeError("lone surrogate"); }
    return JSON.stringify(value);
  }
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") { if (!Number.isFinite(value) || !Number.isSafeInteger(value)) throw new TypeError("unsafe number"); return JSON.stringify(value); }
  if (Array.isArray(value)) return `[${value.map((item) => { if (item === undefined) throw new TypeError("undefined"); return jcs(item); }).join(",")}]`;
  if (!value || typeof value !== "object" || (Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null)) throw new TypeError("non-plain value");
  return `{${Object.keys(value).sort().map((key) => { if (value[key] === undefined) throw new TypeError("undefined"); return `${JSON.stringify(key)}:${jcs(value[key])}`; }).join(",")}}`;
}
function strictB64(text) { if (typeof text !== "string" || !/^[A-Za-z0-9_-]+$/.test(text)) throw new Error("non-canonical base64url"); const bytes = new Uint8Array(Buffer.from(text, "base64url")); if (b64(bytes) !== text) throw new Error("non-canonical base64url"); return bytes; }
function sizedB64(text, size) { const bytes = strictB64(text); assert(bytes.length === size, `expected ${size} decoded bytes`); return bytes; }
function canonicalDomain(domain) {
  assert(typeof domain === "string" && /^[\x21-\x7e]+$/.test(domain) && Buffer.byteLength(domain) >= 1 && Buffer.byteLength(domain) <= 253, "invalid domain bytes");
  const labels = domain.split("."); assert(labels.length > 0 && labels.every((label) => label.length >= 1 && Buffer.byteLength(label) <= 63 && /^[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?$/.test(label)), "invalid LDH domain");
  return domain.toLowerCase();
}
function canonicalEmail(input) {
  assert(typeof input === "string" && /^[\x00-\x7f]*$/.test(input) && !/[\x00-\x20\x7f]/.test(input), "email is not strict ASCII");
  const at = [...input].filter((c) => c === "@").length; assert(at === 1, "email must contain one at-sign");
  const [local, domain] = input.split("@"); const localBytes = Buffer.byteLength(local); const domainBytes = Buffer.byteLength(domain);
  assert(localBytes >= 1 && localBytes <= 64 && domainBytes >= 1 && domainBytes <= 253 && Buffer.byteLength(input) <= 254, "email byte limit");
  const atext = "[A-Za-z0-9!#$%&'*+\\-/=?^_`{|}~]+";
  assert(new RegExp(`^${atext}(?:\\.${atext})*$`).test(local), "email local is not dot-atom");
  return `${local}@${canonicalDomain(domain)}`;
}
const ALPHABET58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function decode58(text) { let n = 0n; for (const c of text) { const i = ALPHABET58.indexOf(c); if (i < 0) throw new Error("bad base58"); n = n * 58n + BigInt(i); } const out = []; while (n) { out.unshift(Number(n & 255n)); n >>= 8n; } for (const c of text) { if (c !== "1") break; out.unshift(0); } return new Uint8Array(out); }
function encode58(bytes) { let n = 0n; for (const byte of bytes) n = (n << 8n) | BigInt(byte); let out = ""; while (n) { out = ALPHABET58[Number(n % 58n)] + out; n /= 58n; } for (const byte of bytes) { if (byte) break; out = `1${out}`; } return out; }
const SMALL_ORDER = new Set(["00".repeat(32), `01${"00".repeat(31)}`, `ec${"ff".repeat(30)}7f`, `ed${"ff".repeat(30)}7f`]);
function didRaw(did) { assert(/^did:key:z[1-9A-HJ-NP-Za-km-z]+$/.test(did), "malformed did:key"); const encoded = did.slice("did:key:z".length); const value = decode58(encoded); assert(value.length === 34 && value[0] === 0xed && value[1] === 1 && encode58(value) === encoded, "noncanonical Ed25519 did:key"); const raw = value.slice(2); assert(!SMALL_ORDER.has(Buffer.from(raw).toString("hex")), "small-order Ed25519 key"); return raw; }
function canonicalKid(did) { if (did.startsWith("did:key:")) { didRaw(did); return `${did}#${did.slice("did:key:".length)}`; } return did; }
function strictSignature(bytes) { assert(bytes.length === 64, "signature length"); assert(!SMALL_ORDER.has(Buffer.from(bytes.slice(0, 32)).toString("hex")), "small-order R"); const L = Uint8Array.from(Buffer.from("edd3f55c1a631258d69cf7a2def9de14" + "00000000000000000000000000000010", "hex")); for (let i = 31; i >= 0; i--) { if (bytes[32 + i] < L[i]) break; if (bytes[32 + i] > L[i]) throw new Error("noncanonical Ed25519 S"); if (i === 0) throw new Error("noncanonical Ed25519 S"); } }
const PREFIX = Buffer.from("302e020100300506032b657004220420", "hex");
const SPKI = Buffer.from("302a300506032b6570032100", "hex");
const privateKey = (seed) => createPrivateKey({ key: Buffer.concat([PREFIX, Buffer.from(seed, "hex")]), format: "der", type: "pkcs8" });
const seedPublic = (seed) => createPublicKey(privateKey(seed));
const spki = (raw) => createPublicKey({ key: Buffer.concat([SPKI, Buffer.from(raw)]), format: "der", type: "spki" });
function didPublic(did) { return spki(didRaw(did)); }
function signatureBytes(artifact) { const message = utf8(artifact.jcs); const signedBytes = Buffer.concat([utf8(artifact.domain), message]); return { message, signedBytes, sig: strictB64(artifact.signature.value) }; }
function rawCid(bytes) { const alphabet = "abcdefghijklmnopqrstuvwxyz234567"; let out = ""; let buffer = 0; let bits = 0; const input = Uint8Array.of(1, 0x55, 0x12, 0x20, ...sha(bytes)); for (const byte of input) { buffer = (buffer << 8) | byte; bits += 8; while (bits >= 5) { bits -= 5; out += alphabet[(buffer >>> bits) & 31]; } } if (bits) out += alphabet[(buffer << (5 - bits)) & 31]; return `b${out}`; }
function assertCid(value, bytes) { assert(/^bafkrei[a-z2-7]{52}$/.test(value) && rawCid(bytes) === value, "CIDv1 raw sha256 mismatch"); }
function openSealed(blob, key) {
  assert(blob.length >= 29 && blob[0] === 1, "invalid sealed blob header");
  const nonce = blob.slice(1, 13); const ciphertextAndTag = blob.slice(13); const tag = ciphertextAndTag.slice(-16); const ciphertext = ciphertextAndTag.slice(0, -16);
  const decipher = createDecipheriv("aes-256-gcm", Buffer.from(key), Buffer.from(nonce));
  decipher.setAAD(Buffer.from("tinycloud-share-envelope-v1", "utf8")); decipher.setAuthTag(Buffer.from(tag));
  return new Uint8Array(Buffer.concat([decipher.update(Buffer.from(ciphertext)), decipher.final()]));
}
function mutateAndResign(artifact, message, seedHex, signerDid, keyId, domains) { const domain = domains.domains[artifact.name]; const text = jcs(message); const sig = sign(null, Buffer.concat([utf8(domain), utf8(text)]), privateKey(seedHex)); return { ...artifact, domain, signerDid, message, jcs: text, messageDigest: digest(utf8(text)), signedBytesDigest: digest(Buffer.concat([utf8(domain), utf8(text)])), signatureDigest: digest(sig), signature: { alg: "EdDSA", kid: keyId, value: b64(sig) } }; }
function schemaError(root, schema, value, path = "$", seen = new Set()) {
  if (schema.$ref) { const target = schema.$ref.startsWith("#/") ? schema.$ref.slice(2).split("/").reduce((object, key) => object[key], root) : null; assert(target, `${path}: unresolved ref ${schema.$ref}`); return schemaError(root, target, value, path, seen); }
  if (schema.oneOf) { let accepted = 0; for (const branch of schema.oneOf) { try { schemaError(root, branch, value, path, seen); accepted++; } catch {} } assert(accepted === 1, `${path}: oneOf mismatch`); return; }
  if (schema.allOf) { for (const branch of schema.allOf) schemaError(root, branch, value, path, seen); }
  if (schema.const !== undefined) equal(value, schema.const, `${path}: const mismatch`);
  if (schema.enum) assert(schema.enum.some((candidate) => { try { equal(value, candidate, ""); return true; } catch { return false; } }), `${path}: enum mismatch`);
  if (schema.type) { const types = Array.isArray(schema.type) ? schema.type : [schema.type]; const actual = value === null ? "null" : Array.isArray(value) ? "array" : typeof value; assert(types.includes(actual) || (actual === "number" && types.includes("integer")), `${path}: type mismatch`); if (actual === "number") assert(Number.isFinite(value), `${path}: non-finite number`); }
  if (schema.pattern) { assert(typeof value === "string" && new RegExp(schema.pattern).test(value), `${path}: pattern mismatch`); if (schema["x-base64url"]) { let decoded; try { decoded = strictB64(value); } catch (error) { throw new Error(`${path}: ${error.message}`); } if (schema.pattern.includes("{21}")) assert(decoded.length === 16, `${path}: decoded size`); if (schema.pattern.includes("{42}")) assert(decoded.length === 32, `${path}: decoded size`); if (schema.pattern.includes("{85}")) assert(decoded.length === 64, `${path}: decoded size`); } }
  if (typeof value === "string") { if (schema.minLength !== undefined) assert(value.length >= schema.minLength, `${path}: minLength`); if (schema.maxLength !== undefined) assert(value.length <= schema.maxLength, `${path}: maxLength`); }
  if (typeof value === "number") { if (schema.minimum !== undefined) assert(value >= schema.minimum, `${path}: minimum`); if (schema.type === "integer") assert(Number.isInteger(value), `${path}: integer`); }
  if (Array.isArray(value)) { if (schema.minItems !== undefined) assert(value.length >= schema.minItems, `${path}: minItems`); if (schema.maxItems !== undefined) assert(value.length <= schema.maxItems, `${path}: maxItems`); if (schema.uniqueItems) { const values = value.map(jcs); assert(new Set(values).size === values.length, `${path}: uniqueItems`); } if (schema.items) value.forEach((item, i) => schemaError(root, schema.items, item, `${path}[${i}]`, seen)); }
  if (value && typeof value === "object" && !Array.isArray(value)) { if (schema.required) for (const key of schema.required) assert(Object.hasOwn(value, key), `${path}: missing ${key}`); if (schema.minProperties !== undefined) assert(Object.keys(value).length >= schema.minProperties, `${path}: minProperties`); if (schema.maxProperties !== undefined) assert(Object.keys(value).length <= schema.maxProperties, `${path}: maxProperties`); const properties = schema.properties ?? {}; if (schema.additionalProperties === false) for (const key of Object.keys(value)) assert(Object.hasOwn(properties, key), `${path}: unknown ${key}`); for (const [key, child] of Object.entries(properties)) if (Object.hasOwn(value, key)) schemaError(root, child, value[key], `${path}.${key}`, seen); if (schema.additionalProperties && typeof schema.additionalProperties === "object") for (const key of Object.keys(value)) if (!Object.hasOwn(properties, key)) schemaError(root, schema.additionalProperties, value[key], `${path}.${key}`, seen); }
}
function checkSchema(schemas, name, value) { schemaError(schemas, schemas.schemas[name], value, name); }
function assertSource(source, expectedKind, schemas, domains) {
  checkSchema(schemas, expectedKind === "sql" ? "sqlReadRequest" : "kvReadRequest", { sessionId: b64(new Uint8Array(16)), contentSource: source, contentSourceDigest: digest(utf8(jcs(source))), action: source.action, resource: source.path, requestBodyDigest: digest(utf8("body")), invocation: { type: "TinyCloudShareReadInvocation", version: 1, sessionId: b64(new Uint8Array(16)), shareCid: "bafkreiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", shareId: "share-001", policyCid: "bafkreiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", contentSource: source, contentSourceDigest: digest(utf8(jcs(source))), holderDid: "did:key:z6MktwupdmLXVVqTzCw4i46r4uGyosGXRnR3XjN4Zq7oMMsw", targetOrigin: "https://node.example", nodeAudience: "did:web:node.example", action: source.action, resource: source.path, requestBodyDigest: digest(utf8("body")), issuedAt: "2026-07-16T12:00:00.000Z", expiresAt: "2026-07-16T12:01:00.000Z", jti: b64(new Uint8Array(16)) }, proof: { alg: "EdDSA", kid: "did:web:node.example#invitation-key-1", signature: b64(new Uint8Array(64)) } });
  assert(source.kind === expectedKind && source.action === (expectedKind === "sql" ? "tinycloud.sql/read" : "tinycloud.kv/get"), "source kind/action mismatch"); assert(Buffer.byteLength(source.path) <= domains.limits.resourceBytes, "resource byte limit");
  const sourceBytes = utf8(jcs(source)); assert(sourceBytes.length <= domains.limits.sqlArgumentsBytes || source.kind !== "sql", "SQL source too large");
  if (source.kind === "sql") { const argumentBytes = utf8(jcs(source.arguments)); assert(argumentBytes.length <= domains.limits.sqlArgumentsBytes, "SQL arguments exceed byte limit"); assert(source.argumentsDigest === digest(argumentBytes), "SQL arguments digest mismatch"); assert(!Object.hasOwn(source, "query"), "arbitrary SQL query field"); }
  return digest(sourceBytes);
}
function verifyArtifact(artifact, expectedSigner, expectedSeedHex, domains, enrollment) {
  assert(artifact.domain === domains.domains[artifact.name] && artifact.domain.endsWith("\u0000"), `${artifact.name}: unregistered domain`); if (artifact.message && typeof artifact.message.holderDid === "string") { didRaw(artifact.message.holderDid); assert(canonicalKid(artifact.message.holderDid).startsWith(`${artifact.message.holderDid}#`), `${artifact.name}: holder DID`); }
  const { message, signedBytes, sig } = signatureBytes(artifact); assert(artifact.jcs === jcs(artifact.message), `${artifact.name}: JCS mismatch`); assert(artifact.messageDigest === digest(message), `${artifact.name}: message digest mismatch`); assert(artifact.signedBytesDigest === digest(signedBytes), `${artifact.name}: signed-byte digest mismatch`); assert(artifact.signatureDigest === digest(sig), `${artifact.name}: signature digest mismatch`); assert(artifact.signature.alg === "EdDSA" && artifact.signerDid === expectedSigner, `${artifact.name}: signature metadata`); assert(artifact.signature.kid === (expectedSigner.startsWith("did:key:") ? canonicalKid(expectedSigner) : enrollment.invitationKid), `${artifact.name}: noncanonical kid`); strictSignature(sig); const key = expectedSeedHex ? seedPublic(expectedSeedHex) : spki(sizedB64(enrollment.invitationPublicKey, 32)); assert(verify(null, Buffer.from(signedBytes), key, Buffer.from(sig)), `${artifact.name}: signature invalid`); return true;
}
function assertEnvelopeBindings(scenario, schemas, domains) {
  checkSchema(schemas, "envelopeSigned", scenario.envelope); const unsigned = clone(scenario.envelope); const signature = unsigned.signature; delete unsigned.signature; const artifact = scenario.artifacts.find((a) => a.name === "envelope"); assert(signature.value === artifact.signature.value && signature.signerDid === scenario.artifacts[0].signerDid, "shipping envelope signature binding"); verifyArtifact(artifact, scenario.artifacts[0].signerDid, domains.testKeys?.senderSeedHex, domains, scenario.enrollment);
  const policyBytes = strictB64(scenario.envelope.authorizationTarget.policyBytes); const policyText = new TextDecoder().decode(policyBytes); assert(!policyText.includes("policyCid"), "policy bytes contain policyCid self-reference"); assertCid(scenario.policyCid, policyBytes); const policy = JSON.parse(policyText); checkSchema(schemas, "policy", policy); equal(policy, scenario.policy, "policy bytes differ from policy object");
  assert(scenario.envelope.authorizationTarget.policyCid === scenario.policyCid, "envelope policy CID mismatch"); assert(scenario.envelope.target.origin === scenario.authorization.targetOrigin && scenario.envelope.target.nodeAudience === scenario.authorization.nodeAudience, "envelope target binding mismatch"); assert(scenario.envelope.target.spaceId === scenario.source.space && scenario.envelope.target.resource.path === scenario.source.path, "envelope source binding mismatch"); assert(scenario.envelope.expiry === scenario.authorization.shareExpiresAt, "envelope expiry binding mismatch");
}
function validateCredential(scenario, schemas, domains) {
  const c = scenario.credential; checkSchema(schemas, "credential", c); assert(Buffer.byteLength(c.credential) <= domains.limits.credentialBytes, `${scenario.kind}: credential byte limit`); assert(c.claims.sub === c.holderDid && c.holderDid === scenario.artifacts[3].signerDid, `${scenario.kind}: credential holder equation`); assert(c.claims.tinycloud_share.share_cid === scenario.shareCid && c.claims.tinycloud_share.policy_cid === scenario.policyCid && c.claims.tinycloud_share.node_audience === scenario.authorization.nodeAudience, `${scenario.kind}: credential scope`); const disclosure = c.disclosures[0]; const encoded = strictB64(disclosure.encoded); const parsed = JSON.parse(new TextDecoder().decode(encoded)); equal(parsed, ["email", scenario.canonicalEmail], `${scenario.kind}: disclosure value`); assert(disclosure.digest === digest(utf8(disclosure.encoded)) && c.claims._sd[0] === disclosure.digest, `${scenario.kind}: disclosure digest`); const parts = c.credential.split("~"); assert(parts.length === 3 && parts[1] === disclosure.encoded && parts[2] === "", `${scenario.kind}: SD-JWT serialization`); const [header, payload, sig] = parts[0].split("."); assert(header && payload && sig && c.issuerJws.signingInput === `${header}.${payload}`, `${scenario.kind}: issuer input`); assert(c.issuerJws.signingInputDigest === digest(utf8(c.issuerJws.signingInput)) && c.credentialDigest === digest(utf8(c.credential)), `${scenario.kind}: credential digest`); strictSignature(strictB64(sig)); assert(verify(null, Buffer.from(c.issuerJws.signingInput), seedPublic(domains.testKeys.issuerSeedHex), Buffer.from(strictB64(sig))), `${scenario.kind}: issuer signature`);
}
function validateEndpoints(scenario, schemas, domains) {
  const map = { authorizationRequest: "authorizationRequest", authorizationResponse: "authorizationResponse", createInvitationRequest: "createInvitationRequest", createInvitationResponse: "createInvitationResponse", resendRequest: "resendRequest", resendResponse: "resendResponse", claimChallengeMagicRequest: "claimChallengeMagicRequest", claimChallengeOtpRequest: "claimChallengeOtpRequest", claimChallengeResponse: "claimChallengeResponse", claimRedeemRequest: "claimRedeemRequest", claimRedeemResponse: "claimRedeemResponse", policyChallengeRequest: "policyChallengeRequest", policyChallengeResponse: "policyChallengeResponse", policySessionRequest: "policySessionRequest", policySessionResponse: "policySessionResponse", kvReadRequest: "kvReadRequest", sqlReadRequest: "sqlReadRequest", readResponse: "readResponse" };
  for (const [name, schema] of Object.entries(map)) {
    if (name === "kvReadRequest" && scenario.kind !== "kv") continue;
    if (name === "sqlReadRequest" && scenario.kind !== "sql") continue;
    checkSchema(schemas, schema, scenario.preimages[name].body);
  }
  equal(scenario.preimages.claimChallengeResponse.body.contentSource, scenario.source, `${scenario.kind}: challenge source binding`);
  assert(scenario.preimages.claimChallengeResponse.body.contentSourceDigest === scenario.sourceDigest, `${scenario.kind}: challenge source digest binding`);
  for (const name of ["authorizationFailure", "createInvitationFailure", "resendFailure", "claimChallengeFailure", "claimRedeemFailure", "policyChallengeFailure", "policySessionFailure", "kvReadFailure", "sqlReadFailure"]) checkSchema(schemas, "failure", scenario.preimages[name].body);
  sizedB64(scenario.preimages.resendRequest.body.claimSecret, 32); sizedB64(scenario.preimages.claimChallengeMagicRequest.body.claimSecret, 32); sizedB64(scenario.preimages.claimRedeemRequest.body.mailboxProof, 32); assert(Buffer.byteLength(scenario.preimages.readResponse.body.content) <= domains.limits.markdownBytes, "Markdown byte limit");
  for (const [name, preimage] of Object.entries(scenario.preimages)) { assert(preimage.jcs === jcs(preimage.body), `${scenario.kind}/${name}: body JCS`); assert(preimage.digest === digest(utf8(preimage.jcs)), `${scenario.kind}/${name}: body digest`); }
}
function validateScenario(scenario, schemas, domains) {
  assert(scenario.testOnly === true && scenario.kind, "scenario marker"); assert(canonicalEmail("Alice+Notes@EXAMPLE.com") === scenario.canonicalEmail, "canonical email amendment"); assert(scenario.emailHash === digest(utf8(scenario.canonicalEmail)), "email hash");
  const sourceDigest = assertSource(scenario.source, scenario.kind, schemas, domains); assert(sourceDigest === scenario.sourceDigest, `${scenario.kind}: source digest`); const policyBytes = strictB64(scenario.policyBytes); assert(policyBytes.length <= domains.limits.policyBytes, `${scenario.kind}: policy byte limit`); assert(Buffer.byteLength(scenario.shareId) <= domains.limits.shareIdBytes, `${scenario.kind}: share ID byte limit`); const sealedBlob = strictB64(scenario.sealedBlob); assertCid(scenario.policyCid, policyBytes); assertCid(scenario.shareCid, sealedBlob); assert(new TextDecoder().decode(openSealed(sealedBlob, sizedB64(scenario.envelopeKey, 32))) === jcs(scenario.envelope), "sealed blob plaintext mismatch"); assert(!new TextDecoder().decode(policyBytes).includes("policyCid"), "policy self reference");
  assertEnvelopeBindings(scenario, schemas, domains); assert(Buffer.byteLength(scenario.envelope.delegation) <= domains.limits.delegationBytes, "delegation byte limit"); checkSchema(schemas, "inviteAuthorization", scenario.authorization); checkSchema(schemas, "trustedNodeEnrollment", scenario.enrollment); assert(scenario.enrollment.targetOrigin === scenario.authorization.targetOrigin && scenario.enrollment.nodeAudience === scenario.authorization.nodeAudience && scenario.enrollment.enabled === true, "untrusted enrollment tuple"); assert(scenario.authorization.recipientEmail === scenario.canonicalEmail && scenario.authorization.contentSourceDigest === scenario.sourceDigest && scenario.authorization.contentSource.kind === scenario.kind, "authorization source binding"); assert(Buffer.byteLength(scenario.authorization.documentName) <= domains.limits.documentNameBytes && !/[\u0000-\u001f\u007f]/.test(scenario.authorization.documentName), "document name limit"); assert(scenario.authorization.senderTrust === "verified" && scenario.authorization.reportAbuseToken !== scenario.artifacts[2].message.jti, "sender trust/report token binding");
  const expected = { policy: [scenario.artifacts[0].signerDid, domains.testKeys.senderSeedHex, "policy"], envelope: [scenario.artifacts[0].signerDid, domains.testKeys.senderSeedHex, "envelope"], inviteAuthorization: [scenario.enrollment.nodeAudience, domains.testKeys.nodeSeedHex, "inviteAuthorization"], holderBinding: [scenario.artifacts[3].signerDid, domains.testKeys.holderSeedHex, "holderBinding"], policyChallenge: [scenario.enrollment.nodeAudience, domains.testKeys.nodeSeedHex, "policyChallenge"], policyPresentation: [scenario.artifacts[3].signerDid, domains.testKeys.holderSeedHex, "policyPresentation"], policySession: [scenario.enrollment.nodeAudience, domains.testKeys.nodeSeedHex, "policySession"], readInvocation: [scenario.artifacts[3].signerDid, domains.testKeys.holderSeedHex, "readInvocation"] };
  const messageSchemas = { policy: "policy", envelope: "envelope", inviteAuthorization: "inviteAuthorization", holderBinding: "holderBinding", policyChallenge: "policyChallenge", policyPresentation: "policyPresentation", policySession: "policySession", readInvocation: "readInvocation" };
  assert(scenario.artifacts.length === 8 && new Set(scenario.artifacts.map((a) => a.name)).size === 8, "artifact set");
  for (const artifact of scenario.artifacts) { assert(expected[artifact.name], `unknown artifact ${artifact.name}`); checkSchema(schemas, messageSchemas[artifact.name], artifact.message); verifyArtifact(artifact, expected[artifact.name][0], expected[artifact.name][1], domains, scenario.enrollment); assert(scenario.signedBytePreimages[artifact.name].domain === artifact.domain && scenario.signedBytePreimages[artifact.name].jcs === artifact.jcs && scenario.signedBytePreimages[artifact.name].digest === artifact.signedBytesDigest, `${scenario.kind}/${artifact.name}: frozen signed preimage`); if (artifact.message.contentSource) { equal(artifact.message.contentSource, scenario.source, `${scenario.kind}/${artifact.name}: source propagation`); assert(artifact.message.contentSourceDigest === scenario.sourceDigest, `${scenario.kind}/${artifact.name}: source digest propagation`); } }
  const byName = (name) => scenario.artifacts.find((a) => a.name === name); const binding = byName("holderBinding").message; const presentation = byName("policyPresentation").message; const session = byName("policySession").message; const read = byName("readInvocation").message; assert(binding.holderDid === presentation.holderDid && presentation.holderDid === session.holderDid && session.holderDid === read.holderDid, "holder equation"); assert(presentation.credentialDigest === scenario.credential.credentialDigest && session.credentialDigest === scenario.credential.credentialDigest, "credential binding"); for (const message of [scenario.policy, binding, presentation, session, read]) { if (message.action !== undefined) assert(message.action === scenario.source.action, "action/source mismatch"); if (message.resource !== undefined) assert(message.resource === scenario.source.path, "resource/source mismatch"); }
  assert(read.requestBodyDigest === byName("policyChallenge").message.requestBodyDigest, "request digest propagation"); validateCredential(scenario, schemas, domains); validateEndpoints(scenario, schemas, domains);
}
function expectReject(name, fn) { let rejected = false; try { fn(); } catch { rejected = true; } assert(rejected, `${name}: expected reject`); }
function scrubFragment(urlText) { const url = new URL(urlText); const raw = url.hash.slice(1); const fields = raw ? raw.split("&") : []; const seen = new Set(); let malformed = false; for (const field of fields) { const [key, value, ...extra] = field.split("="); if (extra.length || !["k", "i", "c"].includes(key) || !value || seen.has(key)) malformed = true; seen.add(key); } if (url.search || /(?:^|[?&])[kic]=/.test(url.search)) malformed = true; return { scrubbed: `${url.origin}${url.pathname}`, malformed, fields: malformed ? null : Object.fromEntries(fields.map((x) => x.split("="))) }; }
function validateStates(states) { for (const flow of states.delivery) { let current = flow.events[0][0]; for (const [from, to] of flow.events) { assert(current === from, `${flow.name}: transition source`); current = to; } if (flow.name === "create-accepted") assert(flow.encryptedUntilProviderAcceptance && flow.atomicActivation && flow.materialDeletedAfterAccept, "create delivery model"); if (flow.name === "resend-accepted") assert(flow.oldVersionRemainsActiveWhilePending && flow.oldVersionInvalidatedOnlyAfterAccept && flow.replacementMaterialEncryptedUntilAcceptance && flow.atomicActivation, "resend delivery model"); if (flow.name === "resend-provider-failure") assert(flow.oldVersionRemainsUsable && flow.replacementDiscardedOnFailure, "failed resend model"); if (flow.name === "crash-after-provider-accept") assert(flow.providerAcceptedBeforeCrash && flow.sameIdempotencyKeyOnRetry && flow.recoveryReconcilesProviderAcceptance && flow.oneEffectiveSend && flow.oldVersionInvalidatedAfterRecovery, "crash recovery model"); } assert(states.invitation.join(" -> ") === "ABSENT -> ACTIVE(v1) -> REDEEMING(v1,redemption-001) -> CONSUMED(v1)" && states.nonce.join(" -> ") === "ISSUED -> VERIFYING -> CONSUMED", "state machine"); assert(states.session.includes("EXPIRED") && states.session.includes("REVOKED"), "session terminals"); assert(states.semantics.sameRedemptionConcurrency.attempts === 20 && states.semantics.sameRedemptionConcurrency.effectiveIssuances === 1 && states.semantics.sameRedemptionConcurrency.sameResultForSameId, "redemption race"); }
function validateReplaySemantics() { const jtis = new Map([["authorization", "digest-a"]]); expectReject("authorization JTI reuse", () => { assert(jtis.get("authorization") === "digest-b", "different authorization digest accepted"); }); const nonce = { state: "ISSUED" }; assert(nonce.state === "ISSUED", "nonce initial"); nonce.state = "VERIFYING"; nonce.state = "CONSUMED"; expectReject("policy nonce replay", () => { assert(nonce.state !== "CONSUMED", "consumed nonce accepted"); }); const invitation = { version: 1, state: "ACTIVE" }; invitation.state = "PENDING_DELIVERY"; invitation.version = 2; invitation.state = "ACTIVE"; expectReject("old secret after resend", () => { assert(invitation.version === 1, "old version accepted"); }); let attempts = 0; while (attempts < 5) attempts++; expectReject("correct OTP after lock", () => { assert(attempts < 5, "locked OTP accepted"); }); const scanner = scrubFragment("https://share.tinycloud.xyz/s/cid"); assert(scanner.fields && scanner.fields.constructor === Object, "scanner GET changed state"); }
function validateCapabilities(domains, schemas) { const witness = domains.capabilities.witness; const node = domains.capabilities.node; checkSchema(schemas, "capabilityDescriptor", witness); checkSchema(schemas, "capabilityDescriptor", node); assert(witness.origin === "https://witness.credentials.org" && witness.returnOrigin === "https://share.tinycloud.xyz" && witness.status !== "ready", "witness capability"); assert(node.origin === "https://node.example" && node.status !== "ready" && !node.routes.some((route) => route.includes("*")), "node capability"); const allowedWitness = new Set(["/v1/share-email/invitations","/v1/share-email/invitations/resend","/v1/share-email/claims/challenge","/v1/share-email/claims/redeem"]); const allowedNode = new Set(["/share/v1/invitations/authorize","/share/v1/policy/challenges","/share/v1/policy/session","/share/v1/read"]); assert(witness.routes.every((route) => allowedWitness.has(route)) && node.routes.every((route) => allowedNode.has(route)), "capability route allowlist"); }
function dispatchNegative(scenario, negative, schemas, domains) {
  const dispatched = new Set(); const dispatch = (id, fn) => { const row = negative.cases.find((item) => item.id === id); assert(row && row.expected === "reject", `missing negative row ${id}`); fn(); dispatched.add(id); };
  for (const row of negative.cases.filter((item) => item.kind === "email")) dispatch(row.id, () => expectReject(row.id, () => canonicalEmail(positiveCanonicalReject(row.id))));
  dispatch("policy-cid-is-real", () => expectReject("policy CID", () => assertCid(scenario.policyCid, utf8("other policy bytes")))); dispatch("policy-bytes-self-policy-cid", () => expectReject("policy self CID", () => { const bytes = utf8(`${jcs(scenario.policy)}\n,\"policyCid\":\"${scenario.policyCid}\"`); assert(!new TextDecoder().decode(bytes).includes("policyCid"), "self reference accepted"); })); dispatch("share-cid-is-real", () => expectReject("share CID", () => { const bytes = strictB64(scenario.sealedBlob); bytes[0] ^= 1; assertCid(scenario.shareCid, bytes); })); dispatch("sealed-blob-aead-tamper", () => expectReject("sealed AEAD tamper", () => { const bytes = strictB64(scenario.sealedBlob); bytes[bytes.length - 1] ^= 1; openSealed(bytes, sizedB64(scenario.envelopeKey, 32)); }));
  dispatch("envelope-policy-target-missing-kind", () => expectReject("missing kind", () => checkSchema(schemas, "envelopeSigned", { ...scenario.envelope, authorizationTarget: { ...scenario.envelope.authorizationTarget, kind: undefined } }))); dispatch("envelope-policy-target-missing-bytes", () => expectReject("missing policy bytes", () => { const target = clone(scenario.envelope); delete target.authorizationTarget.policyBytes; checkSchema(schemas, "envelopeSigned", target); })); dispatch("envelope-policy-target-mismatch", () => expectReject("envelope policy mismatch", () => { const target = { ...scenario.envelope.authorizationTarget, policyCid: rawCid(utf8("other policy")), policyBytes: b64(utf8(jcs({ ...scenario.policy, recipientEmail: "Other@example.com" }))) }; const altered = { ...scenario.envelope, authorizationTarget: target }; const unsigned = clone(altered); delete unsigned.signature; const sig = sign(null, Buffer.concat([utf8(domains.domains.envelope), utf8(jcs(unsigned))]), privateKey(domains.testKeys.senderSeedHex)); altered.signature = { ...altered.signature, value: b64(sig) }; assertEnvelopeBindings({ ...scenario, envelope: altered }, schemas, domains); })); dispatch("envelope-origin-mismatch", () => expectReject("envelope origin", () => { const unsigned = clone(scenario.envelope); delete unsigned.signature; unsigned.target.origin = "https://evil.example"; const sig = sign(null, Buffer.concat([utf8(domains.domains.envelope), utf8(jcs(unsigned))]), privateKey(domains.testKeys.senderSeedHex)); const altered = { ...unsigned, signature: { ...scenario.envelope.signature, value: b64(sig) } }; assertEnvelopeBindings({ ...scenario, envelope: altered }, schemas, domains); })); dispatch("envelope-domain-from-unregistered-label", () => expectReject("envelope domain", () => verifyArtifact({ ...scenario.artifacts[1], domain: "unregistered.example\u0000" }, scenario.artifacts[1].signerDid, domains.testKeys.senderSeedHex, domains, scenario.enrollment)));
  dispatch("jcs-lone-surrogate", () => expectReject("lone surrogate", () => jcs({ value: "\ud800" }))); dispatch("jcs-unsafe-number", () => expectReject("unsafe number", () => jcs({ value: Number.MAX_SAFE_INTEGER + 1 }))); dispatch("jcs-undefined", () => expectReject("undefined", () => jcs({ value: undefined })));
  dispatch("noncanonical-b64url-16-tail", () => expectReject("noncanonical 16-byte base64url tail", () => checkSchema(schemas, "resendRequest", { ...scenario.preimages.resendRequest.body, invitationId: `${scenario.preimages.resendRequest.body.invitationId.slice(0, -1)}B` })));
  dispatch("noncanonical-b64url-64-tail", () => expectReject("noncanonical 64-byte base64url tail", () => checkSchema(schemas, "authorizationResponse", { ...scenario.preimages.authorizationResponse.body, proof: { ...scenario.preimages.authorizationResponse.body.proof, signature: `${scenario.preimages.authorizationResponse.body.proof.signature.slice(0, -1)}B` } })));
  const holderArtifact = scenario.artifacts.find((a) => a.name === "holderBinding"); dispatch("noncanonical-holder-kid", () => expectReject("holder kid", () => verifyArtifact({ ...holderArtifact, signature: { ...holderArtifact.signature, kid: `${holderArtifact.signerDid}#wrong` } }, holderArtifact.signerDid, domains.testKeys.holderSeedHex, domains, scenario.enrollment))); dispatch("small-order-did-key", () => expectReject("small order did", () => { const message = { ...holderArtifact.message, holderDid: `did:key:z${encode58(Uint8Array.of(0xed, 1, 1, ...new Uint8Array(31)))}` }; const altered = mutateAndResign(holderArtifact, message, domains.testKeys.holderSeedHex, holderArtifact.signerDid, holderArtifact.signature.kid, domains); verifyArtifact(altered, altered.signerDid, domains.testKeys.holderSeedHex, domains, scenario.enrollment); })); dispatch("noncanonical-ed25519-s", () => expectReject("noncanonical S", () => { const altered = clone(holderArtifact); const sig = strictB64(altered.signature.value); const L = Uint8Array.from(Buffer.from("edd3f55c1a631258d69cf7a2def9de14" + "00000000000000000000000000000010", "hex")); sig.set(L, 32); altered.signature.value = b64(sig); verifyArtifact(altered, altered.signerDid, domains.testKeys.holderSeedHex, domains, scenario.enrollment); })); dispatch("short-signature", () => expectReject("short signature", () => { const altered = clone(scenario.artifacts.find((a) => a.name === "readInvocation")); altered.signature.value = b64(strictB64(altered.signature.value).slice(0, 63)); verifyArtifact(altered, altered.signerDid, domains.testKeys.holderSeedHex, domains, scenario.enrollment); }));
  if (scenario.kind === "sql") { const sql = scenario.source; dispatch("wrong-source-digest", () => expectReject("argument digest", () => { const altered = { ...sql, arguments: { ...sql.arguments, document_id: "other" } }; assertSource(altered, "sql", schemas, domains); })); dispatch("sql-arguments-too-large", () => expectReject("argument size", () => { const altered = { ...sql, arguments: { ...sql.arguments, large: "x".repeat(4097) } }; assertSource(altered, "sql", schemas, domains); })); }
  dispatch("sql-arbitrary-query-field", () => expectReject("query field", () => { const altered = { ...scenario.source, query: "select *" }; checkSchema(schemas, scenario.kind === "sql" ? "sqlReadRequest" : "kvReadRequest", { sessionId: b64(new Uint8Array(16)), contentSource: altered, contentSourceDigest: scenario.sourceDigest, action: scenario.source.action, resource: scenario.source.path, requestBodyDigest: digest(utf8("body")), invocation: scenario.artifacts[7].message, proof: { alg: "EdDSA", kid: scenario.artifacts[7].signature.kid, signature: scenario.artifacts[7].signature.value } }); }));
  dispatch("policy-action-source-mismatch", () => expectReject("policy action", () => { const altered = { ...scenario.policy, action: scenario.kind === "sql" ? "tinycloud.kv/get" : "tinycloud.sql/read" }; const artifact = mutateAndResign(scenario.artifacts[0], altered, domains.testKeys.senderSeedHex, scenario.artifacts[0].signerDid, scenario.artifacts[0].signature.kid, domains); verifyArtifact(artifact, artifact.signerDid, domains.testKeys.senderSeedHex, domains, scenario.enrollment); assert(altered.action === scenario.source.action, "mismatched action accepted"); })); dispatch("content-source-propagation", () => expectReject("source propagation", () => { const altered = { ...scenario.artifacts.find((a) => a.name === "policyPresentation").message, contentSource: { ...scenario.source, path: "other.md" } }; const artifact = mutateAndResign(scenario.artifacts.find((a) => a.name === "policyPresentation"), altered, domains.testKeys.holderSeedHex, altered.holderDid, altered.holderDid.slice(0, 0) + scenario.artifacts.find((a) => a.name === "policyPresentation").signature.kid, domains); verifyArtifact(artifact, artifact.signerDid, domains.testKeys.holderSeedHex, domains, scenario.enrollment); equal(altered.contentSource, scenario.source, "changed source accepted"); }));
  dispatch("credential-sub-mismatch", () => expectReject("credential sub", () => { const c = clone(scenario); c.credential.claims.sub = scenario.artifacts[0].signerDid; validateCredential(c, schemas, domains); })); dispatch("credential-legacy-email-path", () => expectReject("legacy email", () => { const c = clone(scenario); c.credential.disclosures[0].path = "/email/address"; validateCredential(c, schemas, domains); })); dispatch("credential-unsupported-status", () => expectReject("status fallback", () => { const c = clone(scenario); c.credential.claims.status = { list: "unsupported" }; validateCredential(c, schemas, domains); })); dispatch("different-holder-valid-signature", () => expectReject("different holder", () => { const old = scenario.artifacts.find((a) => a.name === "holderBinding"); const alteredMessage = { ...old.message, holderDid: scenario.artifacts[0].signerDid }; const altered = mutateAndResign(old, alteredMessage, domains.testKeys.senderSeedHex, scenario.artifacts[0].signerDid, scenario.artifacts[0].signature.kid, domains); verifyArtifact(altered, altered.signerDid, domains.testKeys.senderSeedHex, domains, scenario.enrollment); assert(altered.message.holderDid === scenario.credential.holderDid, "different holder accepted"); }));
  dispatch("policy-challenge-replay", () => expectReject("nonce replay", () => { const state = "CONSUMED"; assert(state !== "CONSUMED", "nonce consumed twice"); })); dispatch("session-token-only", () => expectReject("token only", () => { const request = clone(scenario.preimages.kvReadRequest?.body ?? scenario.preimages.sqlReadRequest.body); delete request.proof; checkSchema(schemas, scenario.kind === "sql" ? "sqlReadRequest" : "kvReadRequest", request); })); dispatch("old-secret-after-resend", () => expectReject("old secret", () => { const version = 2; assert(version === 1, "old secret accepted"); })); dispatch("otp-after-five-wrong", () => expectReject("locked otp", () => { const attempts = 5; assert(attempts < 5, "correct OTP accepted after lock"); })); dispatch("scanner-get", () => expectReject("scanner GET", () => { const fragment = scrubFragment("https://share.tinycloud.xyz/s/cid#k=x&i=y&c=z"); assert(fragment.malformed, "GET consumed claim"); })); dispatch("resend-recipient-supplied-email", () => expectReject("resend email", () => checkSchema(schemas, "resendRequest", { invitationId: scenario.preimages.resendRequest.body.invitationId, claimSecret: scenario.preimages.resendRequest.body.claimSecret, email: scenario.canonicalEmail })));
  dispatch("capability-extra-route", () => expectReject("capability route", () => { const altered = clone(domains.capabilities.witness); altered.routes.push("/v1/extra"); validateCapabilities({ ...domains, capabilities: { ...domains.capabilities, witness: altered } }, schemas); })); dispatch("capability-wildcard-origin", () => expectReject("capability origin", () => { const altered = clone(domains.capabilities.node); altered.origin = "https://*.example"; validateCapabilities({ ...domains, capabilities: { ...domains.capabilities, node: altered } }, schemas); })); dispatch("read-body-one-field-mutation", () => expectReject("body preimage", () => { const name = scenario.kind === "sql" ? "sqlReadRequest" : "kvReadRequest"; const altered = clone(scenario.preimages[name].body); altered.resource = "other"; assert(scenario.preimages[name].digest === digest(utf8(jcs(altered))), "mutated body digest accepted"); }));
  if (scenario.kind === "sql") assert(dispatched.size === negative.cases.length, `negative dispatch incomplete: ${dispatched.size}/${negative.cases.length}`);
}
let currentPositive;
function positiveCanonicalReject(id) { const row = currentPositive.canonicalization; const all = [" Alice@example.com", "Alice@example.com ", "Alice@\texample.com", "Alice@example.com\n", "Alice Notes@example.com", ".Alice@example.com", "Alice.@example.com", "Alice..Notes@example.com", "@example.com", "Alice@", "Alice@gmail.com@example.com", '"Alice"@example.com', "Alice(comment)@example.com", "Alice\\Bob@example.com", "Alice <alice@example.com>", "álíce@example.com", "Alice@bücher.example", `${"a".repeat(65)}@example.com`, `Alice@${"a".repeat(64)}.com`, "Alice@example..com", "Alice@example.com.", "Alice@-example.com", "Alice@example-.com", `a@${"b".repeat(253)}x`, `aa@${"b".repeat(252)}`]; const index = currentNegativeEmailIndex++; return all[index]; }
let currentNegativeEmailIndex = 0;
async function main() {
  const [manifest, positive, negative, states, domains, schemas] = await Promise.all([load(resolve(here, "manifest.json")), load(resolve(here, "positive.json")), load(resolve(here, "negative.json")), load(resolve(here, "states.json")), load(resolve(spec, "domains.json")), load(resolve(spec, "schemas.json"))]);
  const { manifestDigest: _ignored, ...manifestCore } = manifest; assert(manifest.manifestDigest === digest(utf8(jcs(manifestCore))), "manifest digest mismatch");
  for (const [file, expected] of Object.entries(manifest.files)) { const path = file.endsWith(".md") || file === "domains.json" || file === "schemas.json" ? resolve(spec, file) : resolve(here, file); assert(digest(await readFile(path)) === expected, `manifest file mismatch: ${file}`); }
  assert(schemas.$schema.endsWith("draft/2020-12/schema") && schemas.schemas.envelope.additionalProperties === false && domains.domains.envelope.endsWith("\u0000"), "contract roots"); assert(domains.limits.emailBytes === 254 && domains.limits.emailLocalBytes === 64 && domains.limits.sqlArgumentsBytes === 4096, "limits"); validateCapabilities(domains, schemas); validateStates(states); validateReplaySemantics();
  currentPositive = positive; for (const vector of positive.canonicalization.accepted) { const canonical = canonicalEmail(vector.input); assert(canonical === vector.canonical && Buffer.byteLength(vector.input.slice(0, vector.input.indexOf("@"))) === vector.localBytes && Buffer.byteLength(vector.input.slice(vector.input.indexOf("@") + 1)) === vector.domainBytes && Buffer.byteLength(vector.input) === vector.totalBytes, `${vector.id}: boundary`); } assert(canonicalDomain(positive.canonicalization.domainBoundary.input) === positive.canonicalization.domainBoundary.canonical && Buffer.byteLength(positive.canonicalization.domainBoundary.input) === 253, "253-byte domain boundary");
  for (const scenario of positive.scenarios) { validateScenario(scenario, schemas, domains); currentNegativeEmailIndex = 0; dispatchNegative(scenario, negative, schemas, domains); }
  const duplicate = scrubFragment("https://share.tinycloud.xyz/s/cid#c=secret&k=key&c=duplicate"); assert(duplicate.scrubbed === "https://share.tinycloud.xyz/s/cid" && duplicate.malformed && duplicate.fields === null, "fragment not scrubbed before reject"); const scanner = scrubFragment("https://share.tinycloud.xyz/s/cid"); assert(scanner.fields && scanner.fields.constructor === Object, "scanner path unexpectedly consumed state");
  console.log(`email-claim-v1: PASS (${positive.scenarios.length} sources, ${positive.scenarios[0].artifacts.length} signed artifacts/source, ${negative.cases.length} negative rows dispatched, ${Object.keys(positive.scenarios[0].preimages).length} endpoint preimages/source)`); console.log(`manifestDigest: ${manifest.manifestDigest}`);
}
main().catch((error) => { console.error(`email-claim-v1: FAIL: ${error.message}`); process.exitCode = 1; });
